2018-06-01 16:11:16,013 INFO: Two Button startup [in /home/ubuntu/github/python/buttonApp_2/app/__init__.py:47]
2018-06-01 16:11:34,425 ERROR: Exception on /reset_password_request [POST] [in /home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/github/python/buttonApp_2/app/routes.py", line 180, in reset_password_request
    send_password_reset_email(user)
NameError: name 'send_password_reset_email' is not defined
2018-06-01 16:13:05,075 INFO: Two Button startup [in /home/ubuntu/github/python/buttonApp_2/app/__init__.py:47]
2018-06-01 16:13:31,204 ERROR: Exception on /reset_password_request [POST] [in /home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/github/python/buttonApp_2/app/routes.py", line 180, in reset_password_request
    send_password_reset_email(user)
NameError: name 'send_password_reset_email' is not defined
2018-06-01 16:14:24,566 INFO: Two Button startup [in /home/ubuntu/github/python/buttonApp_2/app/__init__.py:47]
2018-06-01 16:14:41,770 ERROR: Exception on /reset_password_request [POST] [in /home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/github/python/buttonApp_2/app/routes.py", line 180, in reset_password_request
    send_password_reset_email(user)
NameError: name 'send_password_reset_email' is not defined
2018-06-01 16:15:53,022 INFO: Two Button startup [in /home/ubuntu/github/python/buttonApp_2/app/__init__.py:47]
2018-06-01 16:16:12,482 ERROR: Exception on /reset_password_request [POST] [in /home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/github/python/buttonApp_2/app/routes.py", line 180, in reset_password_request
    send_password_reset_email(user)
NameError: name 'send_password_reset_email' is not defined
2018-06-01 16:16:38,715 INFO: Two Button startup [in /home/ubuntu/github/python/buttonApp_2/app/__init__.py:47]
2018-06-01 16:16:53,255 ERROR: Exception on /reset_password_request [POST] [in /home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/github/python/buttonApp_2/app/routes.py", line 180, in reset_password_request
    send_password_reset_email(user)
NameError: name 'send_password_reset_email' is not defined
2018-06-01 16:20:59,161 INFO: Two Button startup [in /home/ubuntu/github/python/buttonApp_2/app/__init__.py:47]
2018-06-01 16:21:28,815 ERROR: Exception on /reset_password_request [POST] [in /home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/github/python/buttonApp_2/app/routes.py", line 180, in reset_password_request
    send_password_reset_email(user)
NameError: name 'send_password_reset_email' is not defined
2018-06-01 16:23:15,652 INFO: Two Button startup [in /home/ubuntu/github/python/buttonApp_2/app/__init__.py:47]
2018-06-01 16:25:08,794 INFO: Two Button startup [in /home/ubuntu/github/python/buttonApp_2/app/__init__.py:47]
2018-06-01 16:28:06,368 INFO: Two Button startup [in /home/ubuntu/github/python/buttonApp_2/app/__init__.py:47]
2018-06-01 16:33:54,641 INFO: Two Button startup [in /home/ubuntu/github/python/buttonApp_2/app/__init__.py:47]
2018-06-01 16:34:10,327 INFO: Two Button startup [in /home/ubuntu/github/python/buttonApp_2/app/__init__.py:47]
2018-06-01 16:38:05,836 INFO: Two Button startup [in /home/ubuntu/github/python/buttonApp_2/app/__init__.py:47]
